### ISSUE TITLE
Bad Code

### ISSUE THREAD

**Issue by Fe4Rless233** [nulladmin1/nixos-config#1]
Too many commits 😊😄🌟💫✨🌈🎉🎊🎈🎆🎇🎶🎵🎼🎧🎤🎹🎷🎺🎸🥁🎻📯🎬🎥📽️🎞️📺📻🎮🕹️🎲🧩🎯🎳🎰🎫🎟️🎭🎨🖼️🎪🚀🛸🌠🌌🌍🌎🌏🌞🌝🌚🌜🌛🌙⭐🌟✨💥🔥💧💦🌊🌧️⛅🌦️🌤️🌥️☀️🌦️⛅🌤️🌥️🌦️☀️🌤️⛅🌥️🌦️🌧️⛈️🌩️

**Comment by nulladmin1** [comment]
U right
