### ISSUE TITLE
Hyprland - drm: no renderer attached to backend

### ISSUE THREAD

**Issue by gnussbaum1967** [nulladmin1/nixos-config#2]
Hi,

> Great dots!  I'm trying to use your configs.  I don't have a Nvidia card so I commented out all Nividia instances. Wwhen I go to log into Hyprland from SDDM it crashes with the following:
> 
> [LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 800, y: 600] and format XR24 with modifier 72057594037927935 aka INVALID
> [LOG] [AQ] GBM: Allocated a new buffer with size [Vector2D: x: 800, y: 600] and format XR24 with modifier 72057594037927935 aka INVALID
> [LOG] [AQ] Swapchain: Reconfigured a swapchain to [Vector2D: x: 800, y: 600] XR24 of length 2
> [LOG] CMonitorState::ensureBufferPresent: no buffer or mismatched format, attaching one from the swapchain for modeset being possible
> [ERR] [AQ] drm: No renderer attached to backend
> [ERR] output Virtual-1 failed basic test on format DRM_FORMAT_XRGB8888
> [ERR] [AQ] GBM: Allocating with modifiers failed, falling back to modifier-less allocation
> [ERR] [AQ] GBM: Failed to allocate a GBM buffer: bo null
> [ERR] [AQ] Couldn't allocate a gbm buffer with size [Vector2D: x: 800, y: 600] and format XB24
> [ERR] [AQ] Swapchain: Failed acquiring a buffer
> [ERR] output Virtual-1 failed basic test on format DRM_FORMAT_XBGR8888
> [LOG] CMonitorState::ensureBufferPresent: no buffer or mismatched format, attaching one from the swapchain for modeset being possible

Any ideas on how to fix that?

**Comment by nulladmin1** [comment]
Sorry I took a while to respond, I didn't really anticipate other people to use this. Is it fixed now or is it still an issue? I use `nixos-unstable`, so it generally has a lot of more bleeding-edge updates that might cause problems in an update, and get fixed in another.

**Comment by gnussbaum1967** [comment]
No.  I think it's a mesa issue. I see it in both hyprland and sway

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
[cid:targan_stacked_120x120_gey_blue_3b9461ec-7e55-4702-b1da-8ca47618fcb1.png]


George Nussbaum
Principal Systems Administrator

***@***.***>
        ***@***.***
[cid:phone_ba9dea9f-080e-47c7-9dbd-d1c161a8d667.png]<tel:984-292-0040>  984-292-0040


TARGAN Inc.

[cid:location_79e03efb-877d-46ff-91e6-79b65f657b45.png]<https://goo.gl/maps/tBNAEbne9jogYHt77>  350 E Six Forks Road
Raleigh, NC 27609
[cid:web_130x130_6acdd0a4-9a6b-4bd4-8359-56601442ddbe.png]<http://www.targan.com/>
        www.targan.com

________________________________
This electronic mail message, including any attachments hereto, is intended only for the addressee and may contain privileged and/or confidential information. If you are not the addressee indicated in this message (or responsible for delivery of the message to such person), you are hereby notified that you must not use, disseminate, copy it in any form, or take any action based upon it. If you have received this message by error, please immediately delete it and any copies of it, including any attachments hereto, and notify the sender at TARGAN by reply electronic mail message, fax or phone.
________________________________

**Comment by nulladmin1** [comment]
Oh, okay. Sorry I couldn't help
